HOSTS:
  ubuntu-server-1804-x64:
    roles:
      - master
    platform: ubuntu-1804-amd64
    box: ubuntu/bionic64
    box_url: https://vagrantcloud.com/ubuntu/boxes/bionic64
    hypervisor: vagrant
CONFIG:
  type: foss
  vagrant_ssh_port_random: true
